CREATE TABLE "PR2".VIDEOS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    TITULO VARCHAR(100) NOT NULL,
    AUTOR VARCHAR(100) NOT NULL,
    FECHA VARCHAR(10),
    DURACION VARCHAR(10),
    REPRODUCCIONES INTEGER,
    DESCRIPCION VARCHAR(255),
    FORMATO VARCHAR(10),
    RUTAVIDEO VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE "PR2".USUARIOS
(
	ID INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100),
	APELLIDOS VARCHAR(100),
	EMAIL VARCHAR(100),
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL
);